config/routes.rb
Paypal::Application.routes.draw do
  resources :payment_notifications

  resources :items, only: [:create, :destroy]
  resources :products
  resource :cart

  root 'products#index'

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :products
  has_many :items

def paypal_url(return_url, notify_url)
    values = {
      :business => 'justinseller@example.com',
      :cmd => '_cart',
      :upload => 1,
      :return => return_url,
      :invoice => id,
      :notify_url => notify_url
    }
    # binding.pry
    items.each_with_index do |item, index|
      values.merge!({
        "amount_#{index+1}" => item.price,
        "item_name_#{index+1}" => item.name,
        "item_number_#{index+1}" => item.id,
        "quantity_#{index+1}" => 1
      })
      # binding.pry
    end
    "https://www.sandbox.paypal.com/cgi-bin/webscr?" + values.to_query
  end


end

# :cmd => '_cart', needs to change!!!!!!!!!!!!

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :cart
  belongs_to :product
  delegate :name, to: :product
  delegate :price, to: :product
end

app/models/payment_notification.rb
class PaymentNotification < ActiveRecord::Base
	belongs_to :cart
	serialize :params
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :cart
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

def current_cart
  if Cart.count == 0
    @cart = Cart.create!
    session[:cart_id] = @cart.id
  end
      if session[:cart_id]
    @current_cart = Cart.find(session[:cart_id])
    session[:cart_id] = nil if @current_cart.purchased_at
    end
  if session[:cart_id].nil?
    @current_cart = Cart.create!

    session[:cart_id] = @current_cart.id
  end
  @current_cart
end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

  def show
    @cart = current_cart
 
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def create
    @product = Product.find(params[:product_id])
    @item = Item.create(cart: current_cart, product: @product)
    if @item.save
      flash[:notice] = 'Item added'
      redirect_to cart_path
    else
      flash[:error] = 'NO SOUP FOR YOU'
      redirect_to products_path
    end
  end

end

app/controllers/payment_notifications_controller.rb
class PaymentNotificationsController < ApplicationController
  skip_before_filter :verify_authenticity_token, :only => [:create]
  
  def create
  	 
  	 @payment = PaymentNotification.new()
     @payment.save!
     @cart = Cart.last

     @payment.update_attributes(:params => params, :cart_id => params[:invoice], :status => params[:payment_status], :transaction_id => params[:txn_id])

		 session[:cart_id] = @payment.cart_id
				# binding.pry
   	if @payment.status == "Completed"
			@payment.cart.update_attribute(:purchased_at, Time.now)
		end

		if session[:cart_id]
	    @current_cart ||= Cart.find(session[:cart_id])
	    session[:cart_id] = nil if @current_cart.purchased_at
  	end
  	session[:cart_id]

    render :nothing => true


  end
private
  def payment_params
    params.require(:paymentnotification).permit(:params, :cart_id, :status, :transaction_id)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render action: 'show', status: :created, location: @product }
      else
        format.html { render action: 'new' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :price)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/payment_notifications_helper.rb
module PaymentNotificationsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/carts/show.html.haml
%h1
  Cart for You.
  %ul
    - @cart.items.each do |i|
      %li= "#{i.name}, #{number_to_currency i.price}"

-# %b= "Total: #{number_to_currency @cart.items.pluck(:price)}"
%br
= link_to 'Products', products_path
%br
= link_to 'Pay', @cart.paypal_url(products_url, payment_notifications_url)

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Paypal</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>
      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :price %>
  <%= f.number_field :price, step: 0.01 %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.haml
%h1 Listing products
%table
  %thead
    %tr
      %th
      %th
      %th
  %tbody
    - @products.each do |product|
      %tr
        %td= product.name
        %td= number_to_currency(product.price)
        %td= link_to 'Show', product
        %td= link_to 'Add to cart', items_path(product_id: product.id), method: :post
    %tr
      %td
        %b= number_to_currency @products.pluck(:price).inject(:+)
%br
  = link_to 'New Product', new_product_path
%br
  = link_to 'Check Out', cart_path

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.haml
%h1= @product.name
%h2= number_to_currency @product.price